{{- if .Values.service }}
{{- if .Values.service.ports }}
{{- range $ind , $port := .Values.service.ports }}
{{- if $port.gateway }}
{{- if $port.gateway.enabled }}
{{- if $port.gateway.routes }}
{{- range $key , $route := $port.gateway.routes }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  {{ template "fullname" $ }}-{{ $port.name }}-{{ $key }}-mapping
spec:
{{- if $route.ambassador_id }}
  ambassador_id: {{ $route.ambassador_id }}
{{- else }}
  ambassador_id: gw-{{ $.Release.Namespace }}
{{- end }}
{{- if $route.prefix }}
  prefix: {{ $route.prefix }}
{{- else }}
  prefix: /{{ $.Values.service.name }}/
{{- end }}
  service: {{ $.Values.service.name }}.{{ $.Release.Namespace }}:{{ $port.port }}
{{- if $route.extra }}
{{ toYaml $route.extra | indent 2 }}
{{- end }}
{{- if $route.legacy }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  {{ template "fullname" $ }}-{{ $port.name }}-{{ $key }}-proxy-mapping
spec:
{{- if $route.ambassador_id }}
  ambassador_id: {{ $route.ambassador_id }}
{{- else }}
  ambassador_id: gw-{{ $.Release.Namespace }}
{{- end }}
{{- if $route.prefix }}
  prefix: /proxy{{ $route.prefix }}
{{- else }}
  prefix: /proxy/{{ $.Values.service.name }}/
{{- end }}
  service: {{ $.Values.service.name }}.{{ $.Release.Namespace }}:{{ $port.port }}
{{- if $route.extra }}
{{ toYaml $route.extra | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
